modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
showAsResourcePack=false

[[mods]]
modId="broadcast_radio"
version="0.2.0"
displayName="Broadcast Radio"
authors="Dong_awa"
description='''
电波通讯模组为Minecraft带来了无线电通信系统！
让Minecraft世界充满真实的无线电通信体验！
'''
logoFile="icon.png"

# Forge依赖
[[dependencies.broadcast_radio]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

# MC版本依赖
[[dependencies.broadcast_radio]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"